name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.7.0
  flutter_colorpicker: any

 
  flutter_svg: ^2.0.7
  video_player: ^2.7.0
  audioplayers: ^5.2.0
  flutter_svg_provider: ^1.0.4
  svgator_player_flutter: ^2.0.0
  webview_flutter: ^3.0.4
  flutter_gif: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/animals/
  - assets/memory/
  - assets/animals/sounds/
  - assets/segjumsaman/
  - assets/segjumsaman/sounds/
  - assets/segjumsaman/litir/
  - assets/segjumsaman/islenskdyr/
  - assets/segjumsaman/farataeki/
  - assets/segjumsaman/avextir/
  - assets/segjumsaman/graenmeti/
  - assets/segjumsaman/fot/
  - assets/segjumsaman/dot/
  - assets/segjumsaman/gaeludyr/
  - assets/segjumsaman/husidmitt/
  - assets/segjumsaman/vedur/
  - assets/form/  
  - assets/pairs/
  - assets/litablanda/ 
  - assets/memoryForm/
  - assets/background1.gif